//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by InfoView.rc
//
#define IDR_MANIFEST                    1
#define ID_VERY_BAD                     2
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDS_KERNEL_DLL                  105
#define IDD_PROCESS_INFO_FORM           107
#define IDD_THREADPROPVIEW              108
#define IDD_DIALOGEX                    109
#define IDR_MAINFRAME                   128
#define IDR_INFOVITYPE                  129
#define IDD_GENERAL                     130
#define IDI_OPEN_FOLDER                 130
#define IDD_STYLES                      131
#define IDI_CLOSE_FOLDER                131
#define IDD_CLASS                       132
#define IDR_WINDOWS_POPUPMENU           132
#define IDD_WINDOWS                     133
#define IDD_ABOUTINFOVIEWER             134
#define IDB_AUTHOR_BITMAP               136
#define IDI_GENERAL                     137
#define IDD_FIND_WINDOW                 137
#define IDD_FINDWINDOW                  137
#define IDI_STYLES                      138
#define IDD_THREADS_PROCESSES           138
#define IDD_PROCESSES                   138
#define IDD_95PROCESSES                 138
#define IDI_WINDOWS                     139
#define IDI_CLASSES                     140
#define IDI_FRAME_CIRCLE                141
#define IDI_FRAME                       142
#define IDC_CIRCLE                      143
#define IDI_PROCESSES                   143
#define IDD_FIND_TEXT_DIALOG            148
#define IDD_FINDTEXT                    148
#define IDD_DLL_LIST_DLG                149
#define IDD_DLLLIST                     149
#define IDD_MESSAGES_OPTIONS            150
#define IDD_MSGOPTIONS                  150
#define IDI_DLLICON                     154
#define IDR_PROCESSES_POPUPMENU         158
#define IDR_MESSAGES_POPUPMENU          159
#define IDB_SPLASH_BMP                  162
#define IDD_SPLASH                      163
#define IDD_PROCESS_MEM_INFO            164
#define IDD_NTPROCESSES                 165
#define ID_SHOW_SHOWHIDDENWINDOWS       165
#define ID_HIDE_WINDOW                  166
#define ID_ENABLE_WINDOW                167
#define ID_CLOSE_WINDOW                 168
#define IDD_PROCESS_INFO                173
#define IDR_INFOHOOKDLL1                178
#define IDC_HIDE_WINDOW                 1000
#define IDC_CLASS_NAME                  1000
#define IDC_AUTHOR                      1000
#define IDC_CLOSE_WINDOW                1001
#define IDC_CLASS_STYLE_COMBO           1001
#define IDC_FEEDBACK_STATIC             1001
#define IDC_HOMEPAGE_URL                1001
#define IDC_CLASS_STYLE                 1002
#define IDC_FRAME_ICON                  1002
#define IDC_UNHIDE_WINDOW               1002
#define IDC_STATIC_TEXT                 1003
#define IDC_DISABLE_WINDOW              1003
#define IDC_CLASS_BYTES                 1004
#define IDC_WND_CAPTION                 1005
#define IDC_CLASS_BYTES_COMBO           1005
#define IDC_CHILD_WINDOW                1005
#define IDC_WND_HANDLE                  1006
#define IDC_MENU_NAME                   1006
#define IDC_PARENT_WINDOW               1006
#define IDC_WND_RECTANGLE               1007
#define IDC_ICON_HANDLE                 1007
#define IDC_PREV_WINDOW                 1007
#define IDC_WND_RESTORED_RECT           1008
#define IDC_WND_CLIENT_RECT             1009
#define IDC_CURSOR_HANDLE               1009
#define IDC_STYLES                      1010
#define IDC_WND_PROC                    1010
#define IDC_BKGND_BRUSH                 1010
#define IDC_STATIC_PROCESSID            1010
#define IDC_EX_STYLES                   1011
#define IDC_INSTANCE_HANDLE             1011
#define IDC_STATIC_THREADID             1011
#define IDC_STYLE_LONG                  1012
#define IDC_USER_DATA                   1012
#define IDC_PROCESS_ID                  1012
#define IDC_EX_STYLE_LONG               1013
#define IDC_THREAD_ID                   1013
#define IDC_CONTROL_ID                  1013
#define IDC_HIDE_SPY                    1014
#define IDC_STATIC_THREADID2            1014
#define IDC_STATIC_MODULENAME           1014
#define IDC_NEXT_WINDOW                 1015
#define IDC_STATIC_THREADID3            1015
#define IDC_OWNER_WINDOW                1016
#define IDC_STATIC_CONTROL_ID           1016
#define IDC_PRIORITY_BASE               1017
#define IDC_STATIC_THREADID4            1018
#define IDC_STATIC_NUM_THREADS          1018
#define IDC_HWND                        1019
#define IDC_NUM_THREADS                 1019
#define IDC_CLASSNAME                   1020
#define IDC_STATIC_PARENTPID            1020
#define IDC_FIND                        1022
#define IDC_FIND_EDIT                   1023
#define IDC_RADIO_UP_DIR                1024
#define IDC_RADIO_DOWN_DIR              1025
#define IDC_MATCH_WHOLEWORD             1026
#define IDC_MATCH_CASE                  1027
#define IDC_DLL_LIST                    1029
#define IDC_BUTTON_MSG                  1031
#define IDC_LISTBOX_MSG                 1032
#define IDC_SCROLLBAR_MSG               1033
#define IDC_COMBOBOX_MSG                1034
#define IDC_EDIT_MSG                    1035
#define IDC_TREEVIEW_MSG                1036
#define IDC_LISTVIEW_MSG                1037
#define IDC_DIALOGBOX_MSG               1038
#define IDC_TOOLTIP_MSG                 1039
#define IDC_SPIN_MSG                    1040
#define IDC_TABCTRL_MSG                 1041
#define IDC_TRACKBAR_MSG                1042
#define IDC_STATUSBAR_MSG               1043
#define IDC_PROGRESS_MSG                1044
#define IDC_HOTKEY_MSG                  1045
#define IDC_HEADER_MSG                  1046
#define IDC_ANIMATE_MSG                 1047
#define IDC_DDE_MSG                     1048
#define IDC_UNKNOWN_MSG                 1049
#define IDC_USER_MSG                    1050
#define IDC_MOUSEMOVE_MSG               1051
#define IDC_TOOLBAR_MSG                 1052
#define IDC_PARENT                      1053
#define IDC_CHILD                       1054
#define IDC_SAMETHREAD                  1055
#define IDC_SAMEPROCESS                 1056
#define IDC_WHOLE_SYSTEM                1057
#define IDC_SELECT_ALL                  1058
#define IDC_STATICTEXT1                 1059
#define IDC_STATIC1                     1059
#define IDC_STATICTEXT2                 1060
#define IDC_STATIC2                     1060
#define IDC_STATICTEXT3                 1061
#define IDC_STATIC4                     1061
#define IDC_EMAIL_ID                    1061
#define IDC_STATICTEXT4                 1062
#define IDC_STATIC5                     1062
#define IDC_STATICTEXT5                 1063
#define IDC_STATIC3                     1063
#define IDC_PROCESSID                   1064
#define IDC_THREADID                    1065
#define IDC_SUB_FOLDERS                 1066
#define IDC_MODUE_NAME                  1067
#define IDC_SPLASH_BMP                  1068
#define IDC_INVALID_WINDOW              1069
#define IDC_REFLECT_SELECTION           1070
#define IDC_STATIC_PARENT_PID           1071
#define IDC_PAGEFAULTCOUNT              1073
#define IDC_PEAKWORKINGSETSIZE          1074
#define IDC_WORKINGSETSIZE              1075
#define IDC_QUOTAPEAKPAGEDPOOLUSAGE     1076
#define IDC_QUOTAPAGEDPOOLUSAGE         1077
#define IDC_QUOTAPEAKNONPAGEDPOOLUSAGE  1078
#define IDC_QUOTANONPAGEDPOOLUSAGE      1079
#define IDC_PAGEFILEUSAGE               1080
#define IDC_PEAKPAGEFILEUSAGE           1081
#define IDC_MODULENAME                  1082
#define IDC_MAX_LINES                   1083
#define IDC_COPYLIST                    1084
#define IDC_BUTTON1                     1085
#define IDC_MARKALL                     1085
#define IDC_KEYBOARD_MSG                1089
#define IDC_PROCESS_MODULE_NAME         1098
#define IDC_BTN_REFRESH                 1099
#define IDC_PROCESS_MODULE_NAME2        1099
#define IDC_THREAD_STATE                1099
#define IDC_PROCESS_CURRENT_USAGE       1100
#define IDC_PROCESS_MODULE_NAME3        1100
#define IDC_THREAD_WAIT_REASON          1100
#define IDC_PROCESS_MODULE_NAME4        1101
#define IDC_THREAD_CONTEXT_SWITCHES     1101
#define IDC_PROCESS_MODULE_NAME5        1102
#define IDC_THREAD_CREATION_TIME        1102
#define IDC_PROCESS_PRIORITY_BASE       1103
#define IDC_PROCESS_MODULE_NAME6        1103
#define IDC_THREAD_EXIT_TIME            1103
#define IDC_PROCESS_THREAD_COUNT        1104
#define IDC_PROCESS_MODULE_NAME7        1104
#define IDC_THREAD_KERNEL_TIME          1104
#define IDC_PROCESS_HANDLE_COUNT        1105
#define IDC_PROCESS_MODULE_NAME8        1105
#define IDC_THREAD_USER_TIME            1105
#define IDC_PROCESS_READ_OPERATIONS     1106
#define IDC_PROCESS_WRITE_OPERATIONS    1107
#define IDC_PROCESS_OTHER_OPERATIONS    1108
#define IDC_PROCESS_READ_TRANSFERS      1109
#define IDC_PROCESS_WRITE_TRANSFERS     1110
#define IDC_PROCESS_OTHER_TRANSFERS     1111
#define IDC_PROCESS_CREATION_TIME       1112
#define IDC_PROCESS_EXIT_TIME           1113
#define IDC_PROCESS_KERNEL_TIME         1114
#define IDC_PROCESS_USER_TIME           1115
#define IDC_PROCESS_GDI_OBJECTS_COUNT   1116
#define IDC_PROCESS_USER_OBJECTS_COUNT  1117
#define IDC_PROCESS_PRIORITY            1121
#define IDM_HIGHLIGHT                   32772
#define IDM_SHOWPROPERTIES              32773
#define IDM_ABOUTAUTHOR                 32775
#define IDM_REFRESH                     32776
#define ID_SHIFT_F10                    32777
#define IDM_FIND_WINDOW                 32778
#define IDM_HIDE_WINDOW                 32779
#define IDM_GET_PASSWORD                32783
#define IDM_HIDE_INFOVIEW               32784
#define ID_ENTER                        32786
#define IDM_EXPAND_ALL                  32787
#define ID_MENUITEM32788                32788
#define IDM_EXPAND_ONE_LEVEL            32789
#define IDM_EXPAND_BRANCH               32790
#define IDM_COLLAPSE                    32791
#define IDM_FILE_NEW_WINDOWS            32792
#define IDM_FILE_PROCESS_VIEW           32793
#define IDM_FILE_THREADS_VIEW           32794
#define IDM_FILE_NEW_WINDOWS_VIEW       32795
#define IDM_FIND_TEXT                   32796
#define IDM_SHOW_DLLS                   32797
#define IDM_FILE_NEW_MESSAGES_VIEW      32798
#define IDM_CLEAR_VIEW                  32802
#define IDM_STOP_MESSAGES               32803
#define IDM_START_STOP_MESSAGES         32807
#define IDM_FIND_CAPTION                32809
#define ID_BUTTON32810                  32810
#define ID_UTILS_CREATESHORTCUTONDESKTOP 32811
#define IDM_GET_TEXT                    32812
#define ID_POPUPMENU_COPYTOCLIPBOARD_WINDOWTEXT 32814
#define ID_COPY_WINDOWTEXT              32815
#define ID_POPUPMENU_COPYTOCLIPBOARD_CLASSNAME 32816
#define ID_COPY_CLASSNAME               32817
#define ID_COPY_HWND                    32818
#define ID_COPY_ENTIRETEXT              32819
#define IDM_FILE_NEW_PROCESSES_VIEW     32820
#define IDM_FILE_PROCESS_THREADS        32825
#define ID_DFGDF_GHHGF                  32830
#define ID_PROCESSES_PROPERTIES         32831
#define IDM_KILL_PROCESS                32832
#define ID_SHOW_ONLY_THREADS            32834
#define IDM_ABOUT_INFOVIEW              32835
#define IDM_CHANGE_FONT                 32836
#define IDM_SHOWPROCESS_ID              32837
#define ID_OPTIONS_SHOWTHREADID         32838
#define IDM_SHOW_THREAD_ID              32839
#define IDM_SHOW_CLASSNAME              32840
#define IDM_SHOW_PROCESS_ID             32841
#define ID_OPTIONS_ALWAYSONTOP          32842
#define ID_SHOW_WINDOWCAPTION           32844
#define ID_WINDOWSVIEW_PROPERTIES       32847
#define ID_MESSAGE_PROPERTIES           32848
#define ID_ACCELERATOR32849             32849
#define IDM_FILE_QUIT                   32852
#define IDM_SPY_SHOW                    32858
#define IDM_MESSAGESVIEW_FINDMESSAGE    32865
#define IDM_FILE_NEW_PROCESSES_TREE     32867
#define IDM_COPYWINDOWTOCLIPBOARD       32884
#define ID_WINDOW_CLOSEALLWINDOWS       32885
#define ID_VIEW_FOO                     32886

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        179
#define _APS_NEXT_COMMAND_VALUE         32888
#define _APS_NEXT_CONTROL_VALUE         1138
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
