#include <windows.h>	// includes basic windows functionality
#include <commctrl.h>   // includes the common control header
#include <richedit.h>
#include <WinUser.h>
#include <dde.h>
struct
{
	DWORD MsgID;
	LPTSTR MsgName;
} WindowsMessagesS[] = {
	{ WM_WINDOWPOSCHANGING,		"WM_WINDOWPOSCHANGING"	},
	{ WM_WINDOWPOSCHANGED,		"WM_WINDOWPOSCHANGED"	},
	{ WM_VSCROLLCLIPBOARD,		"WM_VSCROLLCLIPBOARD"	},
	{ WM_VSCROLL,				"WM_VSCROLL"			},
	{ WM_VKEYTOITEM,			"WM_VKEYTOITEM"			},
	{ WM_USERCHANGED,			"WM_USERCHANGED"		},
	{ WM_UNDO,					"WM_UNDO"				},
	{ WM_TIMER,					"WM_TIMER"				},
	{ WM_TIMECHANGE,			"WM_TIMECHANGE"			},
	{ WM_TCARD,					"WM_TCARD"				},
	{ WM_SYSCOMMAND,			"WM_SYSCOMMAND"			},
	{ WM_SYSCOLORCHANGE,		"WM_SYSCOLORCHANGE"		},
	{ WM_STYLECHANGING,			"WM_STYLECHANGING"		},
	{ WM_STYLECHANGED,			"WM_STYLECHANGED"		},
	{ WM_SPOOLERSTATUS,			"WM_SPOOLERSTATUS"		},
	{ WM_SIZING,				"WM_SIZING"				},
	{ WM_SIZECLIPBOARD,			"WM_SIZECLIPBOARD"		},
	{ WM_SIZE,					"WM_SIZE"				},
	{ WM_SHOWWINDOW,			"WM_SHOWWINDOW"			},
	{ WM_SETTINGCHANGE,			"WM_SETTINGCHANGE"		},
	{ WM_SETTEXT,				"WM_SETTEXT"			},
	{ WM_SETREDRAW,				"WM_SETREDRAW"			},
	{ WM_SETICON,				"WM_SETICON"			},
	{ WM_SETHOTKEY,				"WM_SETHOTKEY"			},
	{ WM_SETFONT,				"WM_SETFONT"			},
	{ WM_SETFOCUS,				"WM_SETFOCUS"			},
	{ WM_SETCURSOR,				"WM_SETCURSOR"			},
	{ WM_RENDERFORMAT,			"WM_RENDERFORMAT"		},
	{ WM_RENDERALLFORMATS,		"WM_RENDERALLFORMATS"	},
	{ WM_RBUTTONUP,				"WM_RBUTTONUP"			},
	{ WM_RBUTTONDOWN,			"WM_RBUTTONDOWN"		},
	{ WM_RBUTTONDBLCLK,			"WM_RBUTTONDBLCLK"		},
	{ WM_QUIT,					"WM_QUIT"				},
	{ WM_QUEUESYNC,				"WM_QUEUESYNC"			},
	{ WM_QUERYOPEN,				"WM_QUERYOPEN"			},
	{ WM_QUERYNEWPALETTE,		"WM_QUERYNEWPALETTE"	},
	{ WM_QUERYENDSESSION,		"WM_QUERYENDSESSION"	},
	{ WM_QUERYDRAGICON,			"WM_QUERYDRAGICON"		},
	{ WM_PRINTCLIENT,			"WM_PRINTCLIENT"		},
	{ WM_PRINT,					"WM_PRINT"				},
	{ WM_POWERBROADCAST,		"WM_POWERBROADCAST"		},
	{ WM_POWER,					"WM_POWER"				},
	{ WM_PASTE,					"WM_PASTE"				},
	{ WM_PARENTNOTIFY,			"WM_PARENTNOTIFY"		},
	{ WM_PALETTEISCHANGING,		"WM_PALETTEISCHANGING"  },
	{ WM_PALETTECHANGED,		"WM_PALETTECHANGED"		},
	{ WM_PAINTICON,				"WM_PAINTICON"			},
	{ WM_PAINTCLIPBOARD,		"WM_PAINTCLIPBOARD"		},
	{ WM_PAINT,					"WM_PAINT"				},
	{ WM_NULL,					"WM_NULL"				},
	{ WM_NOTIFYFORMAT,			"WM_NOTIFYFORMAT"		},
	{ WM_NOTIFY,				"WM_NOTIFY"				},
	{ WM_NEXTMENU,				"WM_NEXTMENU"			},
	{ WM_NEXTDLGCTL,			"WM_NEXTDLGCTL"			},
	{ WM_NCRBUTTONUP,			"WM_NCRBUTTONUP"		},
	{ WM_NCRBUTTONDOWN,			"WM_NCRBUTTONDOWN"		},
	{ WM_NCRBUTTONDBLCLK,		"WM_NCRBUTTONDBLCLK"	},
	{ WM_NCPAINT,				"WM_NCPAINT"			},
	{ WM_NCMOUSEMOVE,			"WM_NCMOUSEMOVE"		},
	{ WM_NCMBUTTONUP,			"WM_NCMBUTTONUP"		},
	{ WM_NCMBUTTONDOWN,			"WM_NCMBUTTONDOWN"		},
	{ WM_NCMBUTTONDBLCLK,		"WM_NCMBUTTONDBLCLK"	},
	{ WM_NCLBUTTONUP,			"WM_NCLBUTTONUP"		},
	{ WM_NCLBUTTONDOWN,			"WM_NCLBUTTONDOWN"		},
	{ WM_NCLBUTTONDBLCLK,		"WM_NCLBUTTONDBLCLK"	},
	{ WM_NCHITTEST,				"WM_NCHITTEST"			},
	{ WM_NCDESTROY,				"WM_NCDESTROY"			},
	{ WM_NCCREATE,				"WM_NCCREATE"			},
	{ WM_NCCALCSIZE,			"WM_NCCALCSIZE"			},
	{ WM_NCACTIVATE,			"WM_NCACTIVATE"			},
	{ WM_MOVING,				"WM_MOVING"				},
	{ WM_MOVE,					"WM_MOVE"				},
	{ WM_MOUSEMOVE,				"WM_MOUSEMOVE"			},
	{ WM_MOUSEACTIVATE,			"WM_MOUSEACTIVATE"		},
	{ WM_MENUSELECT,			"WM_MENUSELECT"			},
	{ WM_MENUCHAR,				"WM_MENUCHAR"			},
	{ WM_MEASUREITEM,			"WM_MEASUREITEM"		},
	{ WM_MDITILE,				"WM_MDITILE"			},
	{ WM_MDISETMENU,			"WM_MDISETMENU"			},
	{ WM_MDIRESTORE,			"WM_MDIRESTORE"			},
	{ WM_MDIREFRESHMENU,		"WM_MDIREFRESHMENU"		},
	{ WM_MDINEXT,				"WM_MDINEXT"			},
	{ WM_MDIMAXIMIZE,			"WM_MDIMAXIMIZE"		},
	{ WM_MDIICONARRANGE,		"WM_MDIICONARRANGE"		},
	{ WM_MDIGETACTIVE,			"WM_MDIGETACTIVE"		},
	{ WM_MDIDESTROY,			"WM_MDIDESTROY"			},
	{ WM_MDICREATE,				"WM_MDICREATE"			},
	{ WM_MDICASCADE,			"WM_MDICASCADE"			},
	{ WM_MDIACTIVATE,			"WM_MDIACTIVATE"		},
	{ WM_MBUTTONUP,				"WM_MBUTTONUP"			},
	{ WM_MBUTTONDOWN,			"WM_MBUTTONDOWN"		},
	{ WM_MBUTTONDBLCLK,			"WM_MBUTTONDBLCLK"		},
	{ WM_LBUTTONUP,				"WM_LBUTTONUP"			},
	{ WM_LBUTTONDOWN,			"WM_LBUTTONDOWN"		},
	{ WM_LBUTTONDBLCLK,			"WM_LBUTTONDBLCLK"		},
	{ WM_KILLFOCUS,				"WM_KILLFOCUS"			},
	{ WM_INPUTLANGCHANGEREQUEST,"WM_INPUTLANGCHANGEREQUEST"},
	{ WM_INPUTLANGCHANGE,		"WM_INPUTLANGCHANGE	"	},
	{ WM_INITMENUPOPUP,			"WM_INITMENUPOPUP"		},
	{ WM_INITMENU,				"WM_INITMENU"			},
	{ WM_INITDIALOG,			"WM_INITDIALOG"			},
	{ WM_IME_STARTCOMPOSITION,	"WM_IME_STARTCOMPOSITION"},
	{ WM_IME_SETCONTEXT,		"WM_IME_SETCONTEXT"		},
	{ WM_IME_SELECT,			"WM_IME_SELECT"			},
	{ WM_IME_NOTIFY,			"WM_IME_NOTIFY"			},
	{ WM_IME_KEYUP,				"WM_IME_KEYUP"			},
	{ WM_IME_KEYDOWN,			"WM_IME_KEYDOWN"		},
	{ WM_IME_ENDCOMPOSITION,	"WM_IME_ENDCOMPOSITION" },
	{ WM_IME_CONTROL,			"WM_IME_CONTROL"		},
	{ WM_IME_COMPOSITIONFULL,	"WM_IME_COMPOSITIONFULL"},
	{ WM_IME_COMPOSITION,		"WM_IME_COMPOSITION"	},
	{ WM_IME_CHAR,				"WM_IME_CHAR"			},
	{ WM_ICONERASEBKGND   ,		"WM_ICONERASEBKGND"		},
	{ WM_HSCROLLCLIPBOARD ,		"WM_HSCROLLCLIPBOARD"	},
	{ WM_HSCROLL  ,				"WM_HSCROLL"			},
	{ WM_HOTKEY   ,				"WM_HOTKEY"				},
	{ WM_HELP ,					"WM_HELP"				},
	{ WM_GETTEXTLENGTH,			"WM_GETTEXTLENGTH"		},
	{ WM_GETTEXT  ,				"WM_GETTEXT"			},
	{ WM_GETMINMAXINFO,			"WM_GETMINMAXINFO"		},
	{ WM_GETICON  ,				"WM_GETICON"			},
	{ WM_GETHOTKEY,				"WM_GETHOTKEY"			},
	{ WM_GETFONT  ,				"WM_GETFONT"			},
	{ WM_GETDLGCODE   ,			"WM_GETDLGCODE"			},
	{ WM_FONTCHANGE   ,			"WM_FONTCHANGE"			},
	{ WM_EXITSIZEMOVE ,			"WM_EXITSIZEMOVE"		},
	{ WM_EXITMENULOOP ,			"WM_EXITMENULOOP"		},
	{ WM_ERASEBKGND   ,			"WM_ERASEBKGND"			},
	{ WM_ENTERSIZEMOVE,			"WM_ENTERSIZEMOVE"		},
	{ WM_ENTERMENULOOP,			"WM_ENTERMENULOOP"		},
	{ WM_ENTERIDLE,				"WM_ENTERIDLE"			},
	{ WM_ENDSESSION  ,			"WM_ENDSESSION"			},
	{ WM_ENABLE   ,				"WM_ENABLE"				},
	{ WM_DROPFILES ,			"WM_DROPFILES"			},
	{ WM_DRAWITEM ,				"WM_DRAWITEM"			},
	{ WM_DRAWCLIPBOARD,			"WM_DRAWCLIPBOARD"		},
	{ WM_DISPLAYCHANGE,			"WM_DISPLAYCHANGE"		},
	{ WM_DEVMODECHANGE,			"WM_DEVMODECHANGE"		},
	{ WM_DEVICECHANGE ,			"WM_DEVICECHANGE "		},
	{ WM_DESTROYCLIPBOARD ,		"WM_DESTROYCLIPBOARD"	},
	{ WM_DESTROY  ,				"WM_DESTROY"			},
	{ WM_DELETEITEM   ,			"WM_DELETEITEM"			},
	{ WM_CUT  ,					"WM_CUT"				},
	{ WM_CTLCOLORSTATIC   ,		"WM_CTLCOLORSTATIC"		},
	{ WM_CTLCOLORSCROLLBAR,		"WM_CTLCOLORSCROLLBAR"	},
	{ WM_CTLCOLORMSGBOX   ,		"WM_CTLCOLORMSGBOX"		},
	{ WM_CTLCOLORLISTBOX  ,		"WM_CTLCOLORLISTBOX"	},
	{ WM_CTLCOLOREDIT ,			"WM_CTLCOLOREDIT"		},
	{ WM_CTLCOLORDLG  ,			"WM_CTLCOLORDLG"		},
	{ WM_CTLCOLORBTN  ,			"WM_CTLCOLORBTN"		},
	{ WM_CREATE   ,				"WM_CREATE"				},
	{ WM_COPYDATA ,				"WM_COPYDATA"			},
	{ WM_COPY ,					"WM_COPY"				},
	{ WM_CONTEXTMENU,			"WM_CONTEXTMENU"		},
	{ WM_COMPAREITEM,			"WM_COMPAREITEM"		},
	{ WM_COMPACTING,			"WM_COMPACTING"			},
	{ WM_COMMAND,				"WM_COMMAND"			},
	{ WM_CLOSE,					"WM_CLOSE"				},
	{ WM_CLEAR,					"WM_CLEAR"				},
	{ WM_CHILDACTIVATE,			"WM_CHILDACTIVATE"		},
	{ WM_CHARTOITEM,			"WM_CHARTOITEM"			},
	{ WM_CHANGECBCHAIN,			"WM_CHANGECBCHAIN"		},
	{ WM_CAPTURECHANGED,		"WM_CAPTURECHANGED"		},
	{ WM_CANCELMODE,			"WM_CANCELMODE"			},
	{ WM_CANCELJOURNAL,			"WM_CANCELJOURNAL"		},
	{ WM_ASKCBFORMATNAME,		"WM_ASKCBFORMATNAME"	},
	{ WM_ACTIVATEAPP,			"WM_ACTIVATEAPP"		},
	{ WM_ACTIVATE,				"WM_ACTIVATE"			},
	{ WM_SPOOLERSTATUS,			"WM_SPOOLERSTATUS"		},
	{ WM_PASTE ,				"WM_PASTE "				},
	{ STM_SETIMAGE,				"STM_SETIMAGE"			},
	{ STM_SETICON,				"STM_SETICON"			},
	{ STM_GETIMAGE,				"STM_GETIMAGE"			},
	{ STM_GETICON,				"STM_GETICON"			},
	{ WM_USER,					"WM_USER"				}
};

struct
{
	DWORD MsgID;
	LPTSTR MsgName;
} KeyBoardMessagesS[] = {
	{ WM_KEYDOWN,				"WM_KEYDOWN"				},
	{ WM_KEYUP,					"WM_KEYUP"					},
	{ WM_CHAR,					"WM_CHAR"					},
	{ WM_DEADCHAR,				"WM_DEADCHAR"				},
	{ WM_SYSKEYDOWN,			"WM_SYSKEYDOWN"				},
	{ WM_SYSKEYUP,				"WM_SYSKEYUP"				},
	{ WM_SYSCHAR,				"WM_SYSCHAR"				},
	{ WM_SYSDEADCHAR,			"WM_SYSDEADCHAR"			}
};

struct
{
	DWORD MsgID;
	LPTSTR MsgName;
} ButtonMessagesS[] = {
	{ BM_SETSTYLE,				"BM_SETSTYLE"			},
	{ BM_SETSTATE,				"BM_SETSTATE"			},
	{ BM_SETIMAGE,				"BM_SETIMAGE"			},
	{ BM_SETCHECK,				"BM_SETCHECK"			},
	{ BM_GETSTATE,				"BM_GETSTATE"			},
	{ BM_GETIMAGE,				"BM_GETIMAGE"			},
	{ BM_GETCHECK,				"BM_GETCHECK"			},
	{ BM_CLICK,					"BM_CLICK"				}
};

struct
{
	DWORD MsgID;
	LPTSTR MsgName;
} ButtonNotifyMessagesS[] = {
	{ BN_CLICKED,					"BN_CLICKED"		},
	{ BN_DBLCLK,					"BN_DBLCLK"			},
	{ BN_DISABLE,					"BN_DISABLE"		},
	{ BN_DOUBLECLICKED,				"BN_DOUBLECLICKED"	},
	{ BN_HILITE,					"BN_HILITE"			},
	{ BN_KILLFOCUS,					"BN_KILLFOCUS"		},
	{ BN_PAINT,						"BN_PAINT"			},
	{ BN_PUSHED,					"BN_PUSHED"			},
	{ BN_SETFOCUS,					"BN_SETFOCUS"		},
	{ BN_UNHILITE,					"BN_UNHILITE"		},
	{ BN_UNPUSHED,					"BN_UNPUSHED"		}
};


struct
{
	DWORD MsgID;
	LPTSTR MsgName;
} ListBoxMessagesS[] = {
	{ LB_SETTOPINDEX,			"LB_SETTOPINDEX"		},
	{ LB_SETTABSTOPS,			"LB_SETTABSTOPS"		},
	{ LB_SETSEL,				"LB_SETSEL"				},
	{ LB_SETLOCALE,				"LB_SETLOCALE"			},
	{ LB_SETITEMHEIGHT,			"LB_SETITEMHEIGHT"		},
	{ LB_SETITEMDATA,			"LB_SETITEMDATA"		},
	{ LB_SETHORIZONTALEXTENT,	"LB_SETHORIZONTALEXTENT"},
	{ LB_SETCURSEL,				"LB_SETCURSEL"			},
	{ LB_SETCOUNT,				"LB_SETCOUNT"			},
	{ LB_SETCOLUMNWIDTH,		"LB_SETCOLUMNWIDTH"		},
	{ LB_SETCARETINDEX,			"LB_SETCARETINDEX"		},
	{ LB_SETANCHORINDEX,		"LB_SETANCHORINDEX"		},
	{ LB_SELITEMRANGEEX,		"LB_SELITEMRANGEEX"		},
	{ LB_SELITEMRANGE,			"LB_SELITEMRANGE"		},
	{ LB_SELECTSTRING,			"LB_SELECTSTRING"		},
	{ LB_RESETCONTENT,			"LB_RESETCONTENT"		},
	{ LB_ITEMFROMPOINT,			"LB_ITEMFROMPOINT"		},
	{ LB_INSERTSTRING,			"LB_INSERTSTRING"		},
	{ LB_INITSTORAGE,			"LB_INITSTORAGE"		},
	{ LB_GETTOPINDEX,			"LB_GETTOPINDEX"		},
	{ LB_GETTEXTLEN,			"LB_GETTEXTLEN"			},
	{ LB_GETTEXT,				"LB_GETTEXT"			},
	{ LB_GETSELITEMS,			"LB_GETSELITEMS"		},
	{ LB_GETSELCOUNT,			"LB_GETSELCOUNT"		},
	{ LB_GETSEL,				"LB_GETSEL"				},
	{ LB_GETLOCALE,				"LB_GETLOCALE"			},
	{ LB_GETITEMRECT,			"LB_GETITEMRECT"		},
	{ LB_GETITEMHEIGHT,			"LB_GETITEMHEIGHT"		},
	{ LB_GETITEMDATA,			"LB_GETITEMDATA"		},
	{ LB_GETHORIZONTALEXTENT,	"LB_GETHORIZONTALEXTENT"},
	{ LB_GETCURSEL,				"LB_GETCURSEL"			},
	{ LB_GETCOUNT,				"LB_GETCOUNT"			},
	{ LB_GETCARETINDEX,			"LB_GETCARETINDEX"		},
	{ LB_GETANCHORINDEX,		"LB_GETANCHORINDEX"		},
	{ LB_FINDSTRINGEXACT,		"LB_FINDSTRINGEXACT"	},
	{ LB_FINDSTRING,			"LB_FINDSTRING"			},
	{ LB_DIR,					"LB_DIR"				},
	{ LB_DELETESTRING,			"LB_DELETESTRING"		},
	{ LB_ADDSTRING,				"LB_ADDSTRING"			},
	{ LB_ADDFILE,				"LB_ADDFILE"			}
};


struct
{
	DWORD MsgID;
	LPTSTR MsgName;
} DialogBoxMessagesS[] = {
	{ DM_SETDEFID,				"DM_SETDEFID"			},
	{ DM_REPOSITION,			"DM_REPOSITION"			},
	{ DM_GETDEFID,				"DM_GETDEFID"			}
};

struct
{
	DWORD MsgID;
	LPTSTR MsgName;
} ComboBoxMessagesS[] = {
	{ CB_SHOWDROPDOWN,			"CB_SHOWDROPDOWN"		},
	{ CB_SETTOPINDEX,			"CB_SETTOPINDEX"		},
	{ CB_SETLOCALE,				"CB_SETLOCALE"			},
	{ CB_SETITEMHEIGHT,			"CB_SETITEMHEIGHT"		},
	{ CB_SETITEMDATA,			"CB_SETITEMDATA"		},
	{ CB_SETHORIZONTALEXTENT,	"CB_SETHORIZONTALEXTENT"},
	{ CB_SETEXTENDEDUI,			"CB_SETEXTENDEDUI"		},
	{ CB_SETEDITSEL,			"CB_SETEDITSEL"			},
	{ CB_SETDROPPEDWIDTH,		"CB_SETDROPPEDWIDTH"	},
	{ CB_SETCURSEL,				"CB_SETCURSEL"			},
	{ CB_SELECTSTRING,			"CB_SELECTSTRING"		},
	{ CB_RESETCONTENT,			"CB_RESETCONTENT"		},
	{ CB_LIMITTEXT,				"CB_LIMITTEXT"			},
	{ CB_INSERTSTRING,			"CB_INSERTSTRING"		},
	{ CB_INITSTORAGE,			"CB_INITSTORAGE"		},
	{ CB_GETTOPINDEX,			"CB_GETTOPINDEX"		},
	{ CB_GETLOCALE,				"CB_GETLOCALE"			},
	{ CB_GETLBTEXTLEN,			"CB_GETLBTEXTLEN"		},
	{ CB_GETLBTEXT,				"CB_GETLBTEXT"			},
	{ CB_GETITEMHEIGHT,			"CB_GETITEMHEIGHT"		},
	{ CB_GETITEMDATA,			"CB_GETITEMDATA"		},
	{ CB_GETHORIZONTALEXTENT,	"CB_GETHORIZONTALEXTENT"},
	{ CB_GETEXTENDEDUI,			"CB_GETEXTENDEDUI"		},
	{ CB_GETEDITSEL,			"CB_GETEDITSEL"			},
	{ CB_GETDROPPEDWIDTH,		"CB_GETDROPPEDWIDTH"	},
	{ CB_GETDROPPEDSTATE,		"CB_GETDROPPEDSTATE"	},
	{ CB_GETDROPPEDCONTROLRECT,	"CB_GETDROPPEDCONTROLRECT"},
	{ CB_GETCURSEL,				"CB_GETCURSEL"			},
	{ CB_GETCOUNT,				"CB_GETCOUNT"			},
	{ CB_FINDSTRINGEXACT,		"CB_FINDSTRINGEXACT"	},
	{ CB_FINDSTRING,			"CB_FINDSTRING"			},
	{ CB_DIR,					"CB_DIR"				},
	{ CB_DELETESTRING,			"CB_DELETESTRING"		},
	{ CB_ADDSTRING,				"CB_ADDSTRING"			}
};

struct
{
	DWORD MsgID;
	LPTSTR MsgName;
} EditBoxMessagesS[] = {
	{ EM_UNDO,					"EM_UNDO"				},
	{ EM_STREAMOUT,				"EM_STREAMOUT"			},
	{ EM_STREAMIN,				"EM_STREAMIN"			},
	{ EM_SETWORDWRAPMODE,		"EM_SETWORDWRAPMODE"	},
	{ EM_SETWORDBREAKPROCEX	,	"EM_SETWORDBREAKPROCEX"	},
	{ EM_SETWORDBREAKPROC,		"EM_SETWORDBREAKPROC"	},
	{ EM_SETTARGETDEVICE,		"EM_SETTARGETDEVICE"	},
	{ EM_SETTABSTOPS,			"EM_SETTABSTOPS"		},
	{ EM_SETSEL,				"EM_SETSEL"				},
	{ EM_SETRECTNP,				"EM_SETRECTNP"			},
	{ EM_SETRECT,				"EM_SETRECT"			},
	{ EM_SETREADONLY,			"EM_SETREADONLY"		},
	{ EM_SETPUNCTUATION,		"EM_SETPUNCTUATION"		},
	{ EM_SETPASSWORDCHAR,		"EM_SETPASSWORDCHAR"	},
	{ EM_SETPARAFORMAT,			"EM_SETPARAFORMAT"		},
	{ EM_SETOPTIONS,			"EM_SETOPTIONS"			},
	{ EM_SETOLECALLBACK,		"EM_SETOLECALLBACK"		},
	{ EM_SETMODIFY,				"EM_SETMODIFY"			},
	{ EM_SETMARGINS,			"EM_SETMARGINS"			},
	{ EM_SETLIMITTEXT,			"EM_SETLIMITTEXT"		},
	{ EM_SETIMEOPTIONS,			"EM_SETIMEOPTIONS"		},
	{ EM_SETIMECOLOR,			"EM_SETIMECOLOR"		},
	{ EM_SETHANDLE,				"EM_SETHANDLE"			},
	{ EM_SETEVENTMASK,			"EM_SETEVENTMASK"		},
	{ EM_SETCHARFORMAT,			"EM_SETCHARFORMAT"		},
	{ EM_SETBKGNDCOLOR,			"EM_SETBKGNDCOLOR"		},
	{ EM_SELECTIONTYPE,			"EM_SELECTIONTYPE"		},
	{ EM_SCROLLCARET,			"EM_SCROLLCARET"		},
	{ EM_SCROLL,				"EM_SCROL"				},
	{ EM_REQUESTRESIZE,			"EM_REQUESTRESIZE"		},
	{ EM_REPLACESEL,			"EM_REPLACESEL"			},
	{ EM_POSFROMCHAR,			"EM_POSFROMCHAR"		},
	{ EM_PASTESPECIAL,			"EM_PASTESPECIAL"		},
	{ EM_LINESCROLL,			"EM_LINESCROLL"			},
	{ EM_LINELENGTH,			"EM_LINELENGTH"			},
	{ EM_LINEINDEX,				"EM_LINEINDEX"			},
	{ EM_LINEFROMCHAR,			"EM_LINEFROMCHAR"		},
	{ EM_HIDESELECTION,			"EM_HIDESELECTION"		},
	{ EM_GETWORDWRAPMODE,		"EM_GETWORDWRAPMODE"	},
	{ EM_GETWORDBREAKPROCEX	,	"EM_GETWORDBREAKPROCEX"	},
	{ EM_GETWORDBREAKPROC,		"EM_GETWORDBREAKPROC"	},
	{ EM_GETTHUMB,				"EM_GETTHUMB"			},
	{ EM_GETTEXTRANGE,			"EM_GETTEXTRANGE"		},
	{ EM_GETSELTEXT,			"EM_GETSELTEXT"			},
	{ EM_GETSEL,				"EM_GETSEL"				},
	{ EM_GETRECT,				"EM_GETRECT"			},
	{ EM_GETPUNCTUATION,		"EM_GETPUNCTUATION"		},
	{ EM_GETPASSWORDCHAR,		"EM_GETPASSWORDCHAR"	},
	{ EM_GETPARAFORMAT,			"EM_GETPARAFORMAT"		},
	{ EM_GETOPTIONS,			"EM_GETOPTIONS"			},
	{ EM_GETOLEINTERFACE,		"EM_GETOLEINTERFACE"	},
	{ EM_GETMODIFY,				"EM_GETMODIFY"			},
	{ EM_GETMARGINS,			"EM_GETMARGINS"			},
	{ EM_GETLINECOUNT,			"EM_GETLINECOUNT"		},
	{ EM_GETLINE,				"EM_GETLINE"			},
	{ EM_GETLIMITTEXT,			"EM_GETLIMITTEXT"		},
	{ EM_GETIMEOPTIONS,			"EM_GETIMEOPTIONS"		},
	{ EM_GETIMECOLOR,			"EM_GETIMECOLOR"		},
	{ EM_GETHANDLE,				"EM_GETHANDLE"			},
	{ EM_GETFIRSTVISIBLELINE,	"EM_GETFIRSTVISIBLELINE"},
	{ EM_GETEVENTMASK,			"EM_GETEVENTMASK"		},
	{ EM_GETCHARFORMAT,			"EM_GETCHARFORMAT"		},
	{ EM_FORMATRANGE,			"EM_FORMATRANGE"		},
	{ EM_FMTLINES,				"EM_FMTLINES"			},
	{ EM_FINDWORDBREAK,			"EM_FINDWORDBREAK"		},
	{ EM_FINDTEXTEX,			"EM_FINDTEXTEX"			},
	{ EM_FINDTEXT,				"EM_FINDTEXT"			},
	{ EM_EXSETSEL,				"EM_EXSETSEL"			},
	{ EM_EXLINEFROMCHAR,		"EM_EXLINEFROMCHAR"		},
	{ EM_EXLIMITTEXT,			"EM_EXLIMITTEXT"		},
	{ EM_EXGETSEL,				"EM_EXGETSEL"			},
	{ EM_EMPTYUNDOBUFFER,		"EM_EMPTYUNDOBUFFER"	},
	{ EM_DISPLAYBAND,			"EM_DISPLAYBAND"		},
	{ EM_CHARFROMPOS,			"EM_CHARFROMPOS"		},
	{ EM_CANUNDO,				"EM_CANUNDO"			},
	{ EM_CANPASTE,				"EM_CANPASTE"			}
};

struct
{
	DWORD MsgID;
	LPTSTR MsgName;
} DDEMessagesS[] = {
	{ WM_DDE_UNADVISE,			"WM_DDE_UNADVISE"		},
	{ WM_DDE_TERMINATE,			"WM_DDE_TERMINATE"		},
	{ WM_DDE_REQUEST,			"WM_DDE_REQUEST"		},
	{ WM_DDE_POKE,				"WM_DDE_POKE"			},
	{ WM_DDE_INITIATE,			"WM_DDE_INITIATE"		},
	{ WM_DDE_EXECUTE,			"WM_DDE_EXECUTE"		},
	{ WM_DDE_DATA,				"WM_DDE_DATA"			},
	{ WM_DDE_ADVISE,			"WM_DDE_ADVISE"			},
	{ WM_DDE_ACK,				"WM_DDE_ACK"			}
};

struct
{
	DWORD MsgID;
	LPTSTR MsgName;
} TreeViewMessagesS[] = {
	{ TVM_SORTCHILDRENCB,		"TVM_SORTCHILDRENCB"	},
	{ TVM_SORTCHILDREN,			"TVM_SORTCHILDREN"		},
	{ TVM_SETITEM,				"TVM_SETITEM"			},
	{ TVM_SETINDENT,			"TVM_SETINDENT"			},
	{ TVM_SETIMAGELIST,			"TVM_SETIMAGELIST"		},
	{ TVM_SELECTITEM,			"TVM_SELECTITEM"		},
	{ TVM_INSERTITEM,			"TVM_INSERTITEM"		},
	{ TVM_HITTEST,				"TVM_HITTEST"			},
	{ TVM_GETVISIBLECOUNT,		"TVM_GETVISIBLECOUNT"	},
	{ TVM_GETNEXTITEM,			"TVM_GETNEXTITEM"		},
	{ TVM_GETITEMRECT,			"TVM_GETITEMRECT"		},
	{ TVM_GETITEM,				"TVM_GETITEM"			},
	{ TVM_GETISEARCHSTRING,		"TVM_GETISEARCHSTRING"	},
	{ TVM_GETINDENT,			"TVM_GETINDENT"			},
	{ TVM_GETIMAGELIST,			"TVM_GETIMAGELIST"		},
	{ TVM_GETEDITCONTROL,		"TVM_GETEDITCONTROL"	},
	{ TVM_GETCOUNT,				"TVM_GETCOUNT"			},
	{ TVM_EXPAND,				"TVM_EXPAND"			},
	{ TVM_ENSUREVISIBLE,		"TVM_ENSUREVISIBLE"		},
	{ TVM_ENDEDITLABELNOW,		"TVM_ENDEDITLABELNOW"	},
	{ TVM_EDITLABEL,			"TVM_EDITLABEL"			},
	{ TVM_DELETEITEM,			"TVM_DELETEITEM"		}
};

struct
{
	DWORD MsgID;
	LPTSTR MsgName;
} ToolTipMessagesS[] = {
	{ TTM_UPDATETIPTEXT,		"TTM_UPDATETIPTEXT"		},
	{ TTM_RELAYEVENT,			"TTM_RELAYEVENT"		},
	{ TTM_GETTOOLINFO,			"TTM_GETTOOLINFO"		},
	{ TTM_GETCURRENTTOOL,		"TTM_GETCURRENTTOOL"	},
	{ TTM_ADDTOOL,				"TTM_ADDTOOL"			},
	{ TVM_CREATEDRAGIMAGE,		"TVM_CREATEDRAGIMAGE"	},
	{ TTM_WINDOWFROMPOINT,		"TTM_WINDOWFROMPOINT"	},
	{ TTM_SETTOOLINFO,			"TTM_SETTOOLINFO"		},
	{ TTM_SETDELAYTIME,			"TTM_SETDELAYTIME"		},
	{ TTM_NEWTOOLRECT,			"TTM_NEWTOOLRECT"		},
	{ TTM_HITTEST,				"TTM_HITTEST"			},
	{ TTM_GETTOOLCOUNT,			"TTM_GETTOOLCOUNT"		},
	{ TTM_GETTEXT,				"TTM_GETTEXT"			},
	{ TTM_ENUMTOOLS,			"TTM_ENUMTOOLS"			},
	{ TTM_DELTOOL,				"TTM_DELTOOL"			},
	{ TTM_ACTIVATE,				"TTM_ACTIVATE"			}
};


struct
{
	DWORD MsgID;
	LPTSTR MsgName;
} UpDownCtrlMessagesS[] = {
	{ UDM_SETRANGE,				"UDM_SETRANGE"			},
	{ UDM_SETPOS,				"UDM_SETPOS"			},
	{ UDM_SETBUDDY,				"UDM_SETBUDDY"			},
	{ UDM_SETBASE,				"UDM_SETBASE"			},
	{ UDM_SETACCEL,				"UDM_SETACCEL"			},
	{ UDM_GETRANGE,				"UDM_GETRANGE"			},
	{ UDM_GETPOS,				"UDM_GETPOS"			},
	{ UDM_GETBUDDY,				"UDM_GETBUDDY"			},
	{ UDM_GETBASE,				"UDM_GETBASE"			},
	{ UDM_GETACCEL,				"UDM_GETACCEL"			}
};

struct
{
	DWORD MsgID;
	LPTSTR MsgName;
} TabCtrlMessagesS[] = {
	{ TCM_SETTOOLTIPS,			"TCM_SETTOOLTIPS"		},
	{ TCM_SETPADDING,			"TCM_SETPADDING"		},
	{ TCM_SETITEMSIZE,			"TCM_SETITEMSIZE"		},
	{ TCM_SETITEMEXTRA,			"TCM_SETITEMEXTRA"		},
	{ TCM_SETITEM,				"TCM_SETITEM"			},
	{ TCM_SETIMAGELIST,			"TCM_SETIMAGELIST"		},
	{ TCM_SETCURSEL,			"TCM_SETCURSEL"			},
	{ TCM_SETCURFOCUS,			"TCM_SETCURFOCUS"		},
	{ TCM_REMOVEIMAGE,			"TCM_REMOVEIMAGE"		},
	{ TCM_INSERTITEM,			"TCM_INSERTITEM"		},
	{ TCM_HITTEST,				"TCM_HITTEST"			},
	{ TCM_GETTOOLTIPS,			"TCM_GETTOOLTIPS"		},
	{ TCM_GETROWCOUNT,			"TCM_GETROWCOUNT"		},
	{ TCM_GETITEMRECT,			"TCM_GETITEMRECT"		},
	{ TCM_GETITEMCOUNT,			"TCM_GETITEMCOUNT"		},
	{ TCM_GETITEM,				"TCM_GETITEM"			},
	{ TCM_GETIMAGELIST,			"TCM_GETIMAGELIST"		},
	{ TCM_GETCURSEL,			"TCM_GETCURSEL"			},
	{ TCM_GETCURFOCUS,			"TCM_GETCURFOCUS"		},
	{ TCM_DELETEITEM,			"TCM_DELETEITEM"		},
	{ TCM_DELETEALLITEMS,		"TCM_DELETEALLITEMS"	},
	{ TCM_ADJUSTRECT,			"TCM_ADJUSTRECT"		}
};

struct
{
	DWORD MsgID;
	LPTSTR MsgName;
} TrackBarMessagesS[] = {
	{ TBM_SETTICFREQ,			"TBM_SETTICFREQ"		},
	{ TBM_SETTIC,				"TBM_SETTIC"			},
	{ TBM_SETTHUMBLENGTH,		"TBM_SETTHUMBLENGTH"	},
	{ TBM_SETSELSTART,			"TBM_SETSELSTART"		},
	{ TBM_SETSELEND,			"TBM_SETSELEND"			},
	{ TBM_SETSEL,				"TBM_SETSEL"			},
	{ TBM_SETRANGEMIN,			"TBM_SETRANGEMIN"		},
	{ TBM_SETRANGEMAX,			"TBM_SETRANGEMAX"		},
	{ TBM_SETRANGE,				"TBM_SETRANGE"			},
	{ TBM_SETPOS,				"TBM_SETPOS"			},
	{ TBM_SETPAGESIZE,			"TBM_SETPAGESIZE"		},
	{ TBM_SETLINESIZE,			"TBM_SETLINESIZE"		},
	{ TBM_GETTICPOS,			"TBM_GETTICPOS"			},
	{ TBM_GETTIC,				"TBM_GETTIC"			},
	{ TBM_GETTHUMBRECT,			"TBM_GETTHUMBRECT"		},
	{ TBM_GETTHUMBLENGTH,		"TBM_GETTHUMBLENGTH"	},
	{ TBM_GETSELSTART,			"TBM_GETSELSTART"		},
	{ TBM_GETSELEND,			"TBM_GETSELEND"			},
	{ TBM_GETRANGEMIN,			"TBM_GETRANGEMIN"		},
	{ TBM_GETRANGEMAX,			"TBM_GETRANGEMAX"		},
	{ TBM_GETPTICS,				"TBM_GETPTICS"			},
	{ TBM_GETPOS,				"TBM_GETPOS"			},
	{ TBM_GETPAGESIZE,			"TBM_GETPAGESIZE"		},
	{ TBM_GETNUMTICS,			"TBM_GETNUMTICS"		},
	{ TBM_GETLINESIZE,			"TBM_GETLINESIZE"		},
	{ TBM_GETCHANNELRECT,		"TBM_GETCHANNELRECT"	},
	{ TBM_CLEARTICS,			"TBM_CLEARTICS"			},
	{ TBM_CLEARSEL,				"TBM_CLEARSEL"			}
};

struct
{
	DWORD MsgID;
	LPTSTR MsgName;
} ToolBarMessagesS[] = {
	{ TB_SETTOOLTIPS,			"TB_SETTOOLTIPS"		},
	{ TB_SETSTATE,				"TB_SETSTATE"			},
	{ TB_SETROWS,				"TB_SETROWS"			},
	{ TB_SETPARENT,				"TB_SETPARENT"			},
	{ TB_SETINDENT,				"TB_SETINDENT"			},
	{ TB_SETCMDID,				"TB_SETCMDID"			},
	{ TB_SETBUTTONSIZE,			"TB_SETBUTTONSIZE"		},
	{ TB_SETBITMAPSIZE,			"TB_SETBITMAPSIZE"		},
	{ TB_SAVERESTORE,			"TB_SAVERESTORE"		},
	{ TB_REPLACEBITMAP,			"TB_REPLACEBITMAP"		},
	{ TB_PRESSBUTTON,			"TB_PRESSBUTTON"		},
	{ TB_ISBUTTONPRESSED,		"TB_ISBUTTONPRESSED"	},
	{ TB_ISBUTTONINDETERMINATE,	"TB_ISBUTTONINDETERMINATE"},
	{ TB_ISBUTTONHIDDEN,		"TB_ISBUTTONHIDDEN"		},
	{ TB_ISBUTTONENABLED,		"TB_ISBUTTONENABLED"	},
	{ TB_ISBUTTONCHECKED,		"TB_ISBUTTONCHECKED"	},
	{ TB_INSERTBUTTON,			"TB_INSERTBUTTON"		},
	{ TB_INDETERMINATE,			"TB_INDETERMINATE"		},
	{ TB_HIDEBUTTON,			"TB_HIDEBUTTON"			},
	{ TB_GETTOOLTIPS,			"TB_GETTOOLTIPS"		},
	{ TB_GETSTATE,				"TB_GETSTATE"			},
	{ TB_GETROWS,				"TB_GETROWS"			},
	{ TB_GETITEMRECT,			"TB_GETITEMRECT"		},
	{ TB_GETBUTTONTEXT,			"TB_GETBUTTONTEXT"		},
	{ TB_GETBUTTON,				"TB_GETBUTTON"			},
	{ TB_GETBITMAPFLAGS,		"TB_GETBITMAPFLAGS"		},
	{ TB_GETBITMAP,				"TB_GETBITMAP"			},
	{ TB_ENABLEBUTTON,			"TB_ENABLEBUTTON"		},
	{ TB_DELETEBUTTON,			"TB_DELETEBUTTON"		},
	{ TB_CUSTOMIZE,				"TB_CUSTOMIZE"			},
	{ TB_COMMANDTOINDEX,		"TB_COMMANDTOINDEX"		},
	{ TB_CHECKBUTTON,			"TB_CHECKBUTTON"		},
	{ TB_CHANGEBITMAP,			"TB_CHANGEBITMAP"		},
	{ TB_BUTTONSTRUCTSIZE,		"TB_BUTTONSTRUCTSIZE"	},
	{ TB_BUTTONCOUNT,			"TB_BUTTONCOUNT"		},
	{ TB_AUTOSIZE,				"TB_AUTOSIZE"			},
	{ TB_ADDSTRING,				"TB_ADDSTRING"			},
	{ TB_ADDBUTTONS,			"TB_ADDBUTTONS"			},
	{ TB_ADDBITMAP,				"TB_ADDBITMAP"			}
};


struct
{
	DWORD MsgID;
	LPTSTR MsgName;
}ScrollBarMessages[] = {
	{ SBM_SETSCROLLINFO,		"SBM_SETSCROLLINFO"		},
	{ SBM_SETRANGEREDRAW,		"SBM_SETRANGEREDRAW"	},
	{ SBM_SETRANGE,				"SBM_SETRANGE"			},
	{ SBM_SETPOS,				"SBM_SETPOS"			},
	{ SBM_GETSCROLLINFO,		"SBM_GETSCROLLINFO"		},
	{ SBM_GETRANGE,				"SBM_GETRANGE"			},
	{ SBM_GETPOS,				"SBM_GETPOS"			},
	{ SBM_ENABLE_ARROWS,		"SBM_ENABLE_ARROWS"		}
};


struct
{
	DWORD MsgID;
	LPTSTR MsgName;
}StatusBarMessages[] = {
	{ SB_SIMPLE,				"SB_SIMPLE"				},
	{ SB_SETTEXT,				"SB_SETTEXT"			},
	{ SB_SETPARTS,				"SB_SETPARTS"			},
	{ SB_SETMINHEIGHT,			"SB_SETMINHEIGHT"		},
	{ SB_GETTEXTLENGTH,			"SB_GETTEXTLENGTH"		},
	{ SB_GETTEXT,				"SB_GETTEXT"			},
	{ SB_GETRECT,				"SB_GETRECT"			},
	{ SB_GETPARTS,				"SB_GETPARTS"			},
	{ SB_GETBORDERS,			"SB_GETBORDERS"			}
};

struct
{
	DWORD MsgID;
	LPTSTR MsgName;
}ProgressBarMessages[] = {
	{ PBM_STEPIT,				"PBM_STEPIT"			},
	{ PBM_SETSTEP,				"PBM_SETSTEP"			},
	{ PBM_SETRANGE,				"PBM_SETRANGE"			},
	{ PBM_SETPOS,				"PBM_SETPOS"			},
	{ PBM_DELTAPOS,				"PBM_DELTAPOS"			}
};


struct
{
	DWORD MsgID;
	LPTSTR MsgName;
}ListViewMessages[] = {
	{ LVM_UPDATE,				"LVM_UPDATE"			},
	{ LVM_SORTITEMS,			"LVM_SORTITEMS"			},
	{ LVM_SETTEXTCOLOR,			"LVM_SETTEXTCOLOR"		},
	{ LVM_SETTEXTBKCOLOR,		"LVM_SETTEXTBKCOLOR"	},
	{ LVM_SETITEMTEXT,			"LVM_SETITEMTEXT"		},
	{ LVM_SETITEMSTATE,			"LVM_SETITEMSTATE"		},
	{ LVM_SETITEMPOSITION32,	"LVM_SETITEMPOSITION32"	},
	{ LVM_SETITEMPOSITION,		"LVM_SETITEMPOSITION"	},
	{ LVM_SETITEMCOUNT,			"LVM_SETITEMCOUNT"		},
	{ LVM_SETITEM,				"LVM_SETITEM"			},
	{ LVM_SETIMAGELIST,			"LVM_SETIMAGELIST"		},
	{ LVM_SETCOLUMNWIDTH,		"LVM_SETCOLUMNWIDTH"	},
	{ LVM_SETCOLUMN,			"LVM_SETCOLUMN"			},
	{ LVM_SETCALLBACKMASK,		"LVM_SETCALLBACKMASK"	},
	{ LVM_SETBKCOLOR,			"LVM_SETBKCOLOR"		},
	{ LVM_SCROLL,				"LVM_SCROLL"			},
	{ LVM_REDRAWITEMS,			"LVM_REDRAWITEMS"		},
	{ LVM_INSERTITEM,			"LVM_INSERTITEM"		},
	{ LVM_INSERTCOLUMN,			"LVM_INSERTCOLUMN"		},
	{ LVM_HITTEST,				"LVM_HITTEST"			},
	{ LVM_GETVIEWRECT,			"LVM_GETVIEWRECT"		},
	{ LVM_GETTOPINDEX,			"LVM_GETTOPINDEX"		},
	{ LVM_GETTEXTCOLOR,			"LVM_GETTEXTCOLOR"		},
	{ LVM_GETTEXTBKCOLOR,		"LVM_GETTEXTBKCOLOR"	},
	{ LVM_GETSTRINGWIDTH,		"LVM_GETSTRINGWIDTH"	},
	{ LVM_GETSELECTEDCOUNT,		"LVM_GETSELECTEDCOUNT"	},
	{ LVM_GETORIGIN,			"LVM_GETORIGIN"			},
	{ LVM_GETNEXTITEM,			"LVM_GETNEXTITEM"		},
	{ LVM_GETITEMTEXT,			"LVM_GETITEMTEXT"		},
	{ LVM_GETITEMSTATE,			"LVM_GETITEMSTATE"		},
	{ LVM_GETITEMSPACING,		"LVM_GETITEMSPACING"	},
	{ LVM_GETITEMRECT,			"LVM_GETITEMRECT"		},
	{ LVM_GETITEMPOSITION,		"LVM_GETITEMPOSITION"	},
	{ LVM_GETITEMCOUNT,			"LVM_GETITEMCOUNT"		},
	{ LVM_GETITEM,				"LVM_GETITEM"			},
	{ LVM_GETISEARCHSTRING,		"LVM_GETISEARCHSTRING"	},
	{ LVM_GETIMAGELIST,			"LVM_GETIMAGELIST"		},
	{ LVM_GETEDITCONTROL,		"LVM_GETEDITCONTROL"	},
	{ LVM_GETCOUNTPERPAGE,		"LVM_GETCOUNTPERPAGE"	},
	{ LVM_GETCOLUMNWIDTH,		"LVM_GETCOLUMNWIDTH"	},
	{ LVM_GETCOLUMN,			"LVM_GETCOLUMN"			},
	{ LVM_GETCALLBACKMASK,		"LVM_GETCALLBACKMASK"	},
	{ LVM_GETBKCOLOR,			"LVM_GETBKCOLOR"		},
	{ LVM_FINDITEM,				"LVM_FINDITEM"			},
	{ LVM_ENSUREVISIBLE,		"LVM_ENSUREVISIBLE"		},
	{ LVM_EDITLABEL,			"LVM_EDITLABEL"			},
	{ LVM_DELETEITEM,			"LVM_DELETEITEM"		},
	{ LVM_DELETECOLUMN,			"LVM_DELETECOLUMN"		},
	{ LVM_DELETEALLITEMS,		"LVM_DELETEALLITEMS"	},
	{ LVM_CREATEDRAGIMAGE,		"LVM_CREATEDRAGIMAGE"	},
	{ LVM_ARRANGE,				"LVM_ARRANGE"			}
};


struct
{
	DWORD MsgID;
	LPTSTR MsgName;
}HotkeyMessages[] = {
	{ HKM_SETRULES,				"HKM_SETRULES"			},
	{ HKM_SETHOTKEY,			"HKM_SETHOTKEY"			},
	{ HKM_GETHOTKEY,			"HKM_GETHOTKEY"			}
};


struct
{
	DWORD MsgID;
	LPTSTR MsgName;
}HeaderCtrlMessages[] = {
	{ HDM_SETITEM,				"HDM_SETITEM"			},
	{ HDM_LAYOUT,				"HDM_LAYOUT"			},
	{ HDM_INSERTITEM,			"HDM_INSERTITEM"		},
	{ HDM_HITTEST,				"HDM_HITTEST"			},
	{ HDM_GETITEMCOUNT,			"HDM_GETITEMCOUNT"		},
	{ HDM_GETITEM,				"HDM_GETITEM"			},
	{ HDM_DELETEITEM,			"HDM_DELETEITEM"		}
};


struct
{
	DWORD MsgID;
	LPTSTR MsgName;
}AnimateCtrlMessages[] = {
	{ ACM_STOP,					"ACM_STOP"				},
	{ ACM_PLAY,					"ACM_PLAY"				},
	{ ACM_OPEN,					"ACM_OPEN"				}
};